### ISSUE TITLE
Error message for small data

### ISSUE THREAD

**Issue by saeedfc** [asrhou/NATMI#24]
Hi,
Thanks for the tool. Excited to use this. I was doing a test run with a subset of my data ( 1000 genes 1000 cells). I got the following error. Worked fine when I ran with 10000 genes and 1000 cells. If this is a bigger issue, maybe it will be useful to give a clearer error message than a generic one from pandas:
```
 python ExtractEdges.py --species human --emFile /mnt/DATA1/Fibrosis/Full\ Scale\ Analysis/test_em.csv --annFile /mnt/DATA1/Fibrosis/Full\ Scale\ Analysis/test_metadata.csv --interDB lrc2p --coreNum 20 --out /mnt/DATA1/Fibrosis/Full\ Scale\ Analysis/NATMI/test_out
===================================================
Input data:
Species to obtain abundance data: human
The expression matrix file: /mnt/DATA1/Fibrosis/Full Scale Analysis/test_em.csv
The metafile: /mnt/DATA1/Fibrosis/Full Scale Analysis/test_metadata.csv
The ligand-receptor interaction database: lrc2p.csv
Species to obtain ligand-receptor interactions: human
The number of cores to use: 20
The folder to save all results: /mnt/DATA1/Fibrosis/Full Scale Analysis/NATMI/test_out
===================================================
#### the folder "/mnt/DATA1/Fibrosis/Full Scale Analysis/NATMI/test_out" has been created to save the analysis results
#### cluster the expression matrix
#### generate cell-to-cell interactions
#### extract signaling factors
#### construct signaling interactions
Traceback (most recent call last):
  File "ExtractEdges.py", line 558, in <module>
    main(species, opt.emFile, opt.annFile, idType, interDB, interSpecies, opt.coreNum, opt.out)
  File "ExtractEdges.py", line 468, in main
    GenerateDataFiles(interDB, sumEMDF, meanEMDF, countEMDF, cellEMDF, 'Edges_%s' % (os.path.basename(interDB)), lrM, ann, resultDir, coreNum)
  File "ExtractEdges.py", line 321, in GenerateDataFiles
    edgeListDF = GenerateCell2CellTable(interDB, sumEMDF, meanEMDF, countEMDF, cellEMDF, typeString, lrM, ann, resultDir, coreNum)
  File "ExtractEdges.py", line 311, in GenerateCell2CellTable
    edgeListDF = GenCell2CellEdges(interDB, pairListDF, ligandApprovedSymbolDict, receptorApprovedSymbolDict, coreNum, resultDir)
  File "ExtractEdges.py", line 283, in GenCell2CellEdges
    edgeListDF = pd.concat(fl, axis=0)
  File "/home/luna.kuleuven.be/u0119129/anaconda3/envs/natmi/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 274, in concat
    op = _Concatenator(
  File "/home/luna.kuleuven.be/u0119129/anaconda3/envs/natmi/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

Thanks and Kind regards,
Saeed

**Comment by asrhou** [comment]
Dear Saeed, 

Based on the error message, NATMI did not find any ligand-receptor-mediated communication. I think that is because NATMI cannot find any ligand-receptor pairs in the 1000 genes, while in 10000 genes, NATMI found many ligand-receptor pairs.

Best,
Rui
