### ISSUE TITLE
Duplicated ids in conversion breaks the code

### ISSUE THREAD

**Issue by gershovm** [asrhou/NATMI#33]
Hi,

When running NATMI (docker) on bulk data from mouse with Ensembel IDs the code broke, due to a duplicated entry in ids/10090_ensembl.csv.

The duplicated id is:
ENSMUSG00000115016,AA536875
ENSMUSG00000115016,Gm33906

#### input (test.tsv):
|Gene    | Mhpgs.Ileum     | Mphgs.Colon    | Epithelial.Colon    | Epithelial.Ileum  |
| ------- | ----------------- | ----------------- | --------------------| ----------------- |
|ENSMUSG00000115016 |   63.81654768   |  50.76188162   |  203.3435831  |   373.0936855 |

#### Command
docker run --rm -it --name natmi -v XXX:/opt/NATMI/workdir asrhou/natmi python ExtractEdges.py --species mouse --emFile /opt/NATMI/workdir/test.tsv --coreNum 8 --out /opt/NATMI/workdir/output --idType ensembl
The metafile does not exist, each sample will be considered as a cluster.

#### Output
Input data:
Species to obtain abundance data: mouse
The expression matrix file: /opt/NATMI/workdir/bla.tsv
The metafile is not provided
The ligand-receptor interaction database: lrc2p.csv
Species to obtain ligand-receptor interactions: human
The number of cores to use: 8
The folder to save all results: /opt/NATMI/workdir/output

Traceback (most recent call last):
  File "ExtractEdges.py", line 558, in <module>
    main(species, opt.emFile, opt.annFile, idType, interDB, interSpecies, opt.coreNum, opt.out)
  File "ExtractEdges.py", line 383, in main
    em.index = idT.loc[commonIDs,'Symbol']
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 178, in set_axis

**Comment by asrhou** [comment]
Hi, we obtained the id mapping from MGI, could you remove one of ENSMUSG00000115016 entry? I think this will fix the issue. We will ask an expert to remove duplicated items in the mapping file. Thank you very much for the information!

**Comment by abenjak** [comment]
Hello,
The same occurred to me on human data and Ensembl IDs (error below). The duplicated genes in `9606_ensembl.csv` are
```
ENSG00000230417
ENSG00000230426
```
Removing these genes from the expression matrix solved the problem. I think you should choose one representative entry for these two genes in `9606_ensembl.csv`.

Cheers,
Andrej

```
===================================================
Input data:
Species to obtain abundance data: human
The expression matrix file: ../integrated.seurat.em.tsv
The metafile: ../integrated.seurat.metadata.tsv
The ligand-receptor interaction database: lrc2p.csv
Species to obtain ligand-receptor interactions: human
The number of cores to use: 10
The folder to save all results: ALL
===================================================
Traceback (most recent call last):
  File "ExtractEdges.py", line 558, in <module>
    main(species, opt.emFile, opt.annFile, idType, interDB, interSpecies, opt.coreNum, opt.out)
  File "ExtractEdges.py", line 383, in main
    em.index = idT.loc[commonIDs,'Symbol']
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 178, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 19582 elements, new values have 19583 elements
```
