### ISSUE TITLE
Something error of `Visinteraction` when using toy example 

### ISSUE THREAD

**Issue by eleozzr** [asrhou/NATMI#34]
```bash
#reproduce script 
python ExtractEdges.py --species mouse --emFile toy.sc.em.txt --annFile toy.sc.ann.txt --interDB lrc2p --coreNum 4 --out example
python VisInteractions.py --sourceFolder example --drawClusterPair n --keepTopEdge 15
```

Error information: 
```
Input data:
The source dataset folder: example
The ligand-receptor interaction database: lrc2p
The weight type of cell-to-cell signaling: mean
The detection threshold for interactions to draw is: 0.2
The specicificity threshold for interactions to draw is: 0
The expression threshold for interactions to draw is: 0
Top cluster-to-cluster edges to draw is: 15
The network layout: kk
The font size for cluster labels: 8
The edge width: 0
The maximum radius of the clusters: 0
The relative distance between clusters: 1
The plot width: 12
The plot height: 10
The plot format: pdf
===================================================
#### start to construct the cell-to-cell communication network
#### 575 edges are loaded
#### plotting the weighted directed cell-to-cell communication network
#### the folder "/Users/lixiangjie/Documents/tmp_xumengda/example/Network_exp_0_spe_0_det_0.2_top_15_signal_lrc2p_weight_mean" has been created to save the analysis results
Traceback (most recent call last):
  File "VisInteractions.py", line 951, in DrawGraphvizPlot
    nxgS.draw(plotFileName,prog='fdp') 
  File "/Users/lixiangjie/anaconda3/envs/py36/lib/python3.6/site-packages/pygraphviz/agraph.py", line 1476, in draw
    data = self._run_prog(prog, args)
  File "/Users/lixiangjie/anaconda3/envs/py36/lib/python3.6/site-packages/pygraphviz/agraph.py", line 1341, in _run_prog
    warnings.warn(b"".join(errors).decode(self.encoding), RuntimeWarning)
RuntimeWarning: Warning: node 'Cancer Cell
(5 cells)', graph '' size too small for label
Warning: node 'Endothelial Cells
(2 cells)', graph '' size too small for label
Warning: node 'Neutrophils
(3 cells)', graph '' size too small for label


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "VisInteractions.py", line 2507, in <module>
    MainNetwork(opt.sourceFolder, interDB, weightType, specificityThreshold, weightThreshold, detectionThreshold, keepTopEdge, layout, plotFormat,plotWidth, plotHeight, fontSize, edgeWidth, maxClusterSize, clusterDistance)
  File "VisInteractions.py", line 1327, in MainNetwork
    BuildInterClusterNetwork(origlabels, labels, cltSizes, ccolorList, edgeDF, specificityThreshold, weightThreshold, frequencyThreshold, keepTopEdge, interDB, weightType, layout, plotFormat, plotWidth, plotHeight, fontSize, edgeWidth, maxClusterSize, clusterDistance, resultDir)
  File "VisInteractions.py", line 1126, in BuildInterClusterNetwork
    readmeStr = DrawGraphvizPlot(readmeStr, 'edge-count', 'int', nxgC, adjCountM, dataType, resultDir, plotWidth, plotHeight, fontSize, edgeWidth, colorDict, cltSizeDict, maxClusterSize, wposDictCount, labels, specificityThreshold,weightThreshold,frequencyThreshold,interDB,weightType,layout,plotFormat)
  File "VisInteractions.py", line 959, in DrawGraphvizPlot
    for nd in nxgS.nodes():
  File "/Users/lixiangjie/anaconda3/envs/py36/lib/python3.6/site-packages/pygraphviz/agraph.py", line 388, in nodes
    return list(self.nodes_iter())
DeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f81c8dec390>>
Traceback (most recent call last):
  File "/Users/lixiangjie/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 786, in __del__
    ResourceWarning, source=self)
ResourceWarning: subprocess 74762 is still running
```

**Comment by asrhou** [comment]
Hi, could you increase --plotWidth (default is 12) and --plotHeight (default 10)?
