### ISSUE TITLE
Bulk RNA-Seq analysis does not produce results

### ISSUE THREAD

**Issue by alvarezprado** [asrhou/NATMI#40]
Hi,

Thanks for this fantastic tool, it looks really useful. I've been trying to estimate ligand-receptor mediated interactions using the Docker image and your toy dataset (toy.bulk.em.xls) but I'm getting the following error:

`python ExtractEdges.py --species human --emFile toy.bulk.em.xls --interDB lrc2a --idType ensembl --coreNum 2 --out /mnt/natmi_test`

> The metafile does not exist, each sample will be considered as a cluster.
> ===================================================
> Input data:
> Species to obtain abundance data: human
> The expression matrix file: toy.bulk.em.xls
> The metafile is not provided
> The ligand-receptor interaction database: lrc2a.txt
> Species to obtain ligand-receptor interactions: human
> The number of cores to use: 2
> The folder to save all results: /mnt/natmi_test
> ===================================================
> #### the folder "/mnt/natmi_test" has been created to save the analysis results
> #### cluster the expression matrix
> #### generate cell-to-cell interactions
> #### extract signaling factors
> #### construct signaling interactions
> Traceback (most recent call last):
>   File "ExtractEdges.py", line 558, in <module>
>     main(species, opt.emFile, opt.annFile, idType, interDB, interSpecies, opt.coreNum, opt.out)
>   File "ExtractEdges.py", line 468, in main
>     GenerateDataFiles(interDB, sumEMDF, meanEMDF, countEMDF, cellEMDF, 'Edges_%s' % (os.path.basename(interDB)), lrM, ann, resultDir, coreNum)
>   File "ExtractEdges.py", line 321, in GenerateDataFiles
>     edgeListDF = GenerateCell2CellTable(interDB, sumEMDF, meanEMDF, countEMDF, cellEMDF, typeString, lrM, ann, resultDir, coreNum)
>   File "ExtractEdges.py", line 311, in GenerateCell2CellTable
>     edgeListDF = GenCell2CellEdges(interDB, pairListDF, ligandApprovedSymbolDict, receptorApprovedSymbolDict, coreNum, resultDir)
>   File "ExtractEdges.py", line 283, in GenCell2CellEdges
>     edgeListDF = pd.concat(fl, axis=0)
>   File "/opt/conda/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 281, in concat
>     sort=sort,
>   File "/opt/conda/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 329, in __init__
>     raise ValueError("No objects to concatenate")
> ValueError: No objects to concatenate

Same thing happens when I try to analyze my own bulk samples (sorted populations), am I doing something wrong?

Thanks!

[Ligands_Receptors_lrc2a.xlsx](https://github.com/asrhou/NATMI/files/6142987/Ligands_Receptors_lrc2a.xlsx)

**Comment by alvarezprado** [comment]
My bad, I just realized that the _--idType_ parameter was wrongly assigned as ensembl, if I remove it the toyset is properly analyzed. I guess if I'm getting this error with my samples it means no ligand-receptor interactions detected, right?

Thanks!
