### ISSUE TITLE
error of Visinteraction when using toy example

### ISSUE THREAD

**Issue by noorisotoudeh** [asrhou/NATMI#44]
I have this problem when running toy example data:

python VisInteractions.py --sourceFolder example --drawClusterPair n --keepTopEdge 15
===================================================
Input data:
The source dataset folder: example
The ligand-receptor interaction database: lrc2p
The weight type of cell-to-cell signaling: mean
The detection threshold for interactions to draw is: 0.2
The specicificity threshold for interactions to draw is: 0
The expression threshold for interactions to draw is: 0
Top cluster-to-cluster edges to draw is: 15
The network layout: kk
The font size for cluster labels: 8
The edge width: 0
The maximum radius of the clusters: 0
The relative distance between clusters: 1
The plot width: 12
The plot height: 10
The plot format: pdf
===================================================
#### the folder "/Noori/NATMI/NATMI/example/Network_exp_0_spe_0_det_0.2_top_15_signal_lrc2p_weight_mean" has been created to save the analysis results
Traceback (most recent call last):
  File "/home/req_python/lib/python3.7/site-packages/networkx/convert.py", line 133, in to_networkx_graph
    return nx.from_pandas_dataframe(data, create_using=create_using)
TypeError: from_pandas_dataframe() missing 2 required positional arguments: 'source' and 'target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "VisInteractions.py", line 2510, in <module>
    MainNetwork(opt.sourceFolder, interDB, weightType, specificityThreshold, weightThreshold, detectionThreshold, keepTopEdge, layout, plotFormat,plotWidth, plotHeight, fontSize, edgeWidth, maxClusterSize, clusterDistance)
  File "VisInteractions.py", line 1330, in MainNetwork
    BuildInterClusterNetwork(origlabels, labels, cltSizes, ccolorList, edgeDF, specificityThreshold, weightThreshold, frequencyThreshold, keepTopEdge, interDB, weightType, layout, plotFormat, plotWidth, plotHeight, fontSize, edgeWidth, maxClusterSize, clusterDistance, resultDir)
  File "VisInteractions.py", line 1119, in BuildInterClusterNetwork
    edgeDF, adjM, adjSpecM, adjCountM, nxgW, nxgS, nxgC = BuildAdjM(edgeDF, origlabels, labels, specificityThreshold, weightThreshold, keepTopEdge)
  File "VisInteractions.py", line 230, in BuildAdjM
    nxgW = nx.MultiDiGraph(adjM)
  File "/home/req_python/lib/python3.7/site-packages/networkx/classes/multidigraph.py", line 253, in __init__
    DiGraph.__init__(self, data, **attr)
  File "/home/req_python/lib/python3.7/site-packages/networkx/classes/digraph.py", line 292, in __init__
    convert.to_networkx_graph(data,create_using=self)
  File "/home/req_python/lib/python3.7/site-packages/networkx/convert.py", line 136, in to_networkx_graph
    raise nx.NetworkXError(msg)
networkx.exception.NetworkXError: Input is not a correct Pandas DataFrame.
(req_python) [nsc11@compute-e-16-233 NATMI]$ 

thanks,
Noori

**Comment by asrhou** [comment]
Hi Noori,

Could you tell me what you had done before you ran this command? 

Thanks,
Rui
